In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])
display(a)

array([1, 2, 3, 4])

------------------
- 1D  &#8594; Vector: \[ 1, 2, 3 , 4\] (1D Tensor)
- 2D  &#8594; Matrix: $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ (2D Tensor)
- 3D  &#8594; Cube: \[\[\[1, 2\], \[3 , 4\]\]\] (3D Tensor)
- 4D  &#8594; Tesseract
- 5D  &#8594; ?
...
- nD  &#8594; Tensor

in general we call them **Tensor**

In [5]:
print(f"#Dims: {a.ndim}")
print(f"#Shape: {a.shape}")
print(f"#Type: {a.dtype}")
print(f"#Size: {a.size}")
print(f"#ItemSize: {a.itemsize}")
print(f"#Memory Usage: {a.itemsize * a.size}")
print(f"#Memory Usage: {a.nbytes}")

#Dims: 1
#Shape: (4,)
#Type: int64
#Size: 4
#ItemSize: 8
#Memory Usage: 32
#Memory Usage: 32


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype='uint8')
display(a)

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [8]:
print("#Dims: ", a.ndim)
print("#Shape: ", a.shape)
print("#Type: ", a.dtype)
print("#Size: ", a.size)
print("#ItemSize: ", a.itemsize)
print("#Memory Usage: ", a.itemsize * a.size)
print("#Memory Usage: ", a.nbytes)

#Dims:  2
#Shape:  (2, 3)
#Type:  uint8
#Size:  6
#ItemSize:  1
#Memory Usage:  6
#Memory Usage:  6


In [9]:
a = np.array([[[1],[2],[3]], [[4], [5], [6]]])
display(a)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [10]:
a.ndim

3

In [11]:
a.shape

(2, 3, 1)

In [12]:
# Creates a vector between start & stop with step
np.arange(5, 15, 0.5) 

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [13]:
# Create n numbers between two numbers with fixed length
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.zeros((3,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
a = np.arange(30)

In [20]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
a.reshape((6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [22]:
a.reshape((5,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [23]:
a.reshape((5, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
a = a.reshape((5, -1))

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
np.arange(5).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [27]:
np.arange(5).reshape(1,-1)

array([[0, 1, 2, 3, 4]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.arange(10).reshape(2,5).T.reshape(-1)

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [31]:
np.arange(10).reshape((2,5), order='F')

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [32]:
np.arange(10).reshape((5,2)).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [33]:
a = np.arange(100).reshape(-1, 2)

In [34]:
a.shape

(50, 2)

In [35]:
type(a)

numpy.ndarray

In [36]:
a[10]

array([20, 21])

In [37]:
a[10][0]

20

In [38]:
a[10, 0] 

20

In [39]:
a[2:7]

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [41]:
a[:15]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [42]:
a[-4:]

array([[92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [43]:
a[2:11:2] # [start:stop:step]

array([[ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [44]:
a[:,0] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [46]:
w = 10
h = 10
# GrayScale
a = np.random.randint(0, 255, size=(w,h,3))
display(a[:,:,0])
display(a[:,:,1])
display(a[:,:,2])

array([[ 53, 107,  20, 192, 175, 147, 234,  53, 106,   1],
       [ 20,  84, 123, 243, 201, 119,  98, 107,  48, 171],
       [190, 200,  68,  29,  99, 181, 178, 148, 142, 204],
       [ 31, 128, 132, 163,  85, 213, 146,  75, 237,  30],
       [ 21, 183, 168, 215,  29, 117, 220, 127, 122,  44],
       [130,  57,  93,  27, 108, 184, 245,  52,  76,  10],
       [ 96, 170, 104,   1,   9, 112, 184, 197, 225, 139],
       [136, 223,  10,  99, 231, 218, 160,  38, 109, 253],
       [121, 136,  16,  11,  85, 192, 132, 153, 133, 247],
       [145, 153, 163, 145, 148, 239, 159,  85,  95, 129]])

array([[157, 116, 112, 141, 190,  71,  98, 197,  14, 140],
       [ 88,  80, 109, 103,  96,  12, 212, 184, 251, 192],
       [107,   7, 165,  72, 212,  18, 234,  99, 129, 174],
       [ 81, 216, 254, 196,  58, 152, 117, 118, 183, 107],
       [227, 192, 204,  26,  33,  31, 134, 169, 173, 140],
       [ 79, 236, 247, 208, 169, 206, 110,  58, 198,  86],
       [214, 218, 198, 170,   7,  94, 217, 236,  99, 123],
       [104, 228, 171, 225, 119, 204, 107, 155, 203, 116],
       [ 57,  69,   3, 115,   8, 200, 135, 120,  58,  22],
       [179, 118,  77, 124, 100, 168, 100,  90, 157,  93]])

array([[237,  26, 179, 159, 132, 178,   6,  76, 199,  43],
       [212,  63, 131, 153,  76,  89,  66, 200,  46, 100],
       [171, 159, 186, 129, 216,  11, 105, 201,  43,  97],
       [124,  51,  71,  28, 110,  45, 126,  75,  20, 219],
       [ 79, 105, 187, 145, 246, 154, 104,  97,   6, 113],
       [202,  54,  72, 192,  39, 118, 241, 144, 215, 105],
       [191, 223,  56,  45, 192, 179, 170,  45, 139,  18],
       [234,  73,  39, 205,  39,  70, 103,  90,  19, 230],
       [103,  39, 228,  26, 154,  36, 189, 144, 161,  65],
       [ 92, 130,  72, 244,  19,  47, 254, 163,   2, 159]])

In [47]:
b = np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [48]:
b[::2, 1::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [49]:
b[[0,3], :] 

array([[ 0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23]])

In [50]:
b[[0,2], [3,1]] # -> (0,3) & (2,1) 

array([ 3, 13])

In [51]:
b 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [52]:
b ** 2  # Elementwise operation 

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841]])

In [53]:
b + 2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [54]:
2 + b

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [ ]:
# b.dot(a)   # Matrix Operation

In [55]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [56]:
c = np.ones(6)
c

array([1., 1., 1., 1., 1., 1.])

In [57]:
b + c

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [58]:
d = np.array([1,2,3,4,5,6])
b + d  # Numpy Broadcast

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17],
       [13, 15, 17, 19, 21, 23],
       [19, 21, 23, 25, 27, 29],
       [25, 27, 29, 31, 33, 35]])

In [59]:
d = np.array([1,2,3,4,5,6])
b + d  # Numpy Broadcast

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17],
       [13, 15, 17, 19, 21, 23],
       [19, 21, 23, 25, 27, 29],
       [25, 27, 29, 31, 33, 35]])

In [60]:
np.broadcast_to(d, (5,6))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [61]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
b[[0, 0, -1, -1] , [0,-1, -1, 0]]

array([ 0,  5, 29, 24])

In [63]:
e = np.arange(9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
np.diag(e)

array([0, 4, 8])

In [65]:
e.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [66]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
b % 2

array([[0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1]])

In [68]:
f = b % 2 == 0
f

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [69]:
b[f]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [70]:
b[b%2==0] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [71]:
g = b>5
g

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [72]:
f & g 

array([[False, False, False, False, False, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [73]:
f | g

array([[ True, False,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [74]:
b[(b>3) & (b<8)] 

array([4, 5, 6, 7])

In [75]:
b[~((b>3) & (b<8))] 

array([ 0,  1,  2,  3,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29])